spring.datasource.url=jdbc:mysql://192.168.1.7:3306/innovaeduca
spring.datasource.username=admin
spring.datasource.password=123


# 3. Driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 4. Hibernate (Quitamos la línea del 'dialect' porque causaba error)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

